#include "guicomm_mw.h"
#include "ui_guicomm_mw.h"
#include <stdio.h>
#include <string>
#include <stdlib.h>
#include <iostream>
#include <unistd.h>
#include <ctype.h>
#include <fcntl.h>
#include <errno.h>
#include <QTextStream>
#include <QMessageBox>
#include <QGridLayout>
#include <QVBoxLayout>
#include "module.h"

extern "C"{
#include "/home/dell-kevin/FINS-Framework/FINSCore/fins_headers/finstypes.h"
}

//defines the locations of the two pipes
#define RTM_PIPE_IN "/tmp/fins/rtm_in"
#define RTM_PIPE_OUT "/tmp/fins/rtm_out"


/**********************************
* GUICOMM:
*
* written by Kevin Burns
*
* Description:
* This gui started as a simple GUI (seen in the screenshots at the bottom of my wiki page).
* However after trying to involve configuration files and the new control frame interface.
* I must leave it half implemented. The current error is in loadConfig(), it seems to be caused by string.h
* but could be happening in another thread.
*
* Another problem is linking finstypes.c and .h to this program. The header file works fine.
* Should try to include the entire .o
**********************************/
using namespace std;
QTextStream debug(stdout);

//CONSTRUCTOR:
// loads in the configuration file and sets up the GUI defined in guicomm_mw.ui
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{

    // opens the configuration I define in guicomm.cfg
    // a description of the configuration can be found at the top of the file itself
    try
    {
        cfg.readFile("guicomm.cfg");
    }
    catch (ParseException e)
    {
        debug << "An exception occurred: " << e.getError() << endl;
        exit(1);
    }

    ui->setupUi(this);
    FCF_write_request->dataOrCtrl = 1;
    loadConfig();

    ui->setparam_pb->setEnabled(false); // disables the push button
}

MainWindow::~MainWindow()
{
    delete ui;
}

//generated by QT Creator
void MainWindow::changeEvent(QEvent *e)
{
    QMainWindow::changeEvent(e);
    switch (e->type())
    {
    case QEvent::LanguageChange:
        ui->retranslateUi(this);
        break;
    default:
        break;
    }
}

//Called upon activation of the combobox containing the modules
// Populates the parameter combobox depending on the currently selected module
void MainWindow::on_module_cb_activated(QString selected)
{
    selected_module_qs = selected;
    ui->param_cb->clear();

    if(selected == "<Select>")
    {
        ui->param_cb->addItem("Empty");
    }
    else
    {
        for(int i=0;i<mod_map.size();i++)
        {
            if(selected == mod_map[i].name)
            {
                selected_module_m = mod_map[i];
                QMap<QString, int>::const_iterator ii =  mod_map[i].parameters.constBegin();
                while (ii !=  mod_map[i].parameters.constEnd())
                {
                    ui->param_cb->addItem(ii.key());
                    ++ii;
                }
            }
        }
    }
    readytoSend(); //Checks to see all the CB's have been set up to send a parameter
}

//Called upon activation of the combobox containing the parameters
// sets a class variable to the currently selected parameter
void MainWindow::on_param_cb_activated(QString selected)
{
    selected_param = selected;  //sets the global parameter value to the currently selected parameter
}

//Set parameter push button has been pushed
// Sets the data parameter of the frame to that specified in the textbox
void MainWindow::on_setparam_pb_clicked()
{
     FCF_write_request->ctrlFrame.data = (int*)ui->value_le->text().toInt();

    if(selected_module_m.active)
    {
        FCF_write_request->destinationID.id = selected_module_m.value;
        FCF_write_request->ctrlFrame.name = (unsigned char *)selected_param.toStdString().c_str();
        FCF_write_request->ctrlFrame.opcode = CTRL_SET_PARAM;

        ui->setparam_pb->setEnabled(false);
        ui->value_le->setText("");

        sendtoFINS();
    }
    else
    {
        print_Error("Incorrect feild combination");
    }
    readytoSend();
}

//Called upon activation of the combobox containing the operations
// This will contain logic for the read requests but not the write request
void MainWindow::on_operation_cb_activated(QString selected)
{
    selected_operation = selected;

    //THIS NEED TO BE IMPLEMENTED (THEY ADAPT THE NEW CONTROL FRAMES)

    /*if(selected == Read Realtime)
    {
        read from FINS //create this function, make it return the value. and make it take in the value in the interval fld
        populate the one text box
    }
    else if Read Overtime
    {
        read from FINS
        add a row to the overtime table and display the value
    }
    */

    readytoSend();
}

//Menu->Quit
// Closes the application
void MainWindow::on_actionQuit_triggered()
{
    this->close();
}

//READYTOSEND
// checks to see ifall of the parts of the FINS control frames have been set before enabling the "set parameter" push button
bool MainWindow::readytoSend()
{
    if((FCF_write_request->ctrlFrame.name) && (selected_operation == "Write") && (ui->value_le->text() != ""))
    {
        ui->setparam_pb->setEnabled(true);
   //     print_Status("The value is ready to be written");

        return true;
    }
    else
    {
        ui->setparam_pb->setEnabled(false);
        return false;
    }
}

//SEND TO FINS
void MainWindow::sendtoFINS()
{

    //Initializations
    int rtm_in_fd;		//fildes (unistd.h) used for write()
    int rtm_out_fd;		//fildes (unistd.h)
    int numBytes;
    unsigned char * FCF_cstr;
    QMessageBox mb;
    QString dataOrCtrl_qs;
    QString destinationID_qs;
    QString opcode_qs;
    QString senderID_qs;
    QString serialNum_qs;


    //open the pipe
    rtm_in_fd = open(RTM_PIPE_IN, O_RDWR);
    rtm_out_fd = open(RTM_PIPE_OUT, O_RDWR);

    if (rtm_in_fd == -1)
    {
            print_Error("rtm_in_fd Pipe failure "); //rtm_out_fd???
            exit(EXIT_FAILURE);
    }



    //This is the new method implemented via the finstypes.c and .h
    // Need to solve the linking problem of those two files before uncommenting
/*
   int FCF_cstr_length = serializeCtrlFrame(FCF_write_request,&FCF_cstr);
    numBytes = 0;
    numBytes += write(rtm_in_fd, FCF_cstr, FCF_cstr_length);
*/

    //SEND OVER PIPE RTM_IN
    //DOCUMENT THIS FORMAT
    //This is the old method of sending over the pipe
    //should be moved to another function to be called by the different operation codes
    numBytes = 0;
    numBytes += write(rtm_in_fd, &FCF_write_request->dataOrCtrl, sizeof(unsigned char));
    numBytes += write(rtm_in_fd, &FCF_write_request->destinationID.id, sizeof(unsigned char));
    numBytes += write(rtm_in_fd, &FCF_write_request->ctrlFrame.opcode, sizeof(unsigned short int));
    numBytes += write(rtm_in_fd, &FCF_write_request->ctrlFrame.name, sizeof(unsigned int));
    numBytes += write(rtm_in_fd, &FCF_write_request->ctrlFrame.senderID, sizeof(unsigned char));
    numBytes += write(rtm_in_fd, &FCF_write_request->ctrlFrame.data, sizeof(int));	//sends it over as a int



    //READ FROM PIPE RTM_OUT
    // || Data/Control | Destination_IDs_List | SenderID | Write_parameter_Confirmation_Code | Serial_Number ||
    // old method of reading from the pipe
    // needs to be implemented int he new serializer function
    // Also should be moved to another function to be called by the different operation codes
    numBytes = 0;
    numBytes += read(rtm_out_fd, &FCF_write_reply->dataOrCtrl, sizeof(unsigned char));			//control_data
    numBytes += read(rtm_out_fd, &FCF_write_reply->destinationID.id, sizeof(unsigned char));		//destinationID
    numBytes += read(rtm_out_fd, &FCF_write_reply->ctrlFrame.senderID, sizeof(unsigned char));			//senderID
    numBytes += read(rtm_out_fd, &FCF_write_reply->ctrlFrame.opcode, sizeof(unsigned short int));			//opcode
    numBytes += read(rtm_out_fd, &FCF_write_reply->ctrlFrame.serialNum, sizeof(unsigned int));			//serialNum


    dataOrCtrl_qs = QString::number(FCF_write_reply->dataOrCtrl);
    destinationID_qs = QString::number(FCF_write_reply->destinationID.id);
    opcode_qs = QString::number(FCF_write_reply->ctrlFrame.opcode);
    senderID_qs = QString::number(FCF_write_reply->ctrlFrame.senderID);
    serialNum_qs = QString::number(FCF_write_reply->ctrlFrame.serialNum);

    //Pop-up dialog
    // Shown in the second screenshot on my wiki page
    mb.setText("Parameter has been set!");
    mb.setDetailedText("FCF: dataOrCtrl: " + dataOrCtrl_qs + "\n" +
                       "FCF: destinationID_id: " + destinationID_qs + "\n" +
                       "FCF: opcode: " + opcode_qs + "\n" +
                       "FCF: senderID: " + senderID_qs + "\n" +
                       "FCF: serialNum " + serialNum_qs);
    mb.setStandardButtons( QMessageBox::Ok| QMessageBox::Cancel);
    mb.setDefaultButton(QMessageBox::Ok);
    mb.exec();

    //Command line dialog
    //for  debugging
    print_Status("FCF: dataOrCtrl: " + dataOrCtrl_qs + "\n" +
                 "FCF: destinationID_id: " + destinationID_qs + "\n" +
                 "FCF: opcode: " + opcode_qs + "\n" +
                 "FCF: senderID: " + senderID_qs + "\n" +
                 "FCF: serialNum " + serialNum_qs);

}

//called when a value is entered in the "value_le" textBox
void MainWindow::on_value_le_textEdited(QString )

{
    readytoSend();
}

//used for debugging errors, can be removed
void MainWindow::print_Error(QString print_me)
{
   // ui->status_te->setTextColor(QColor(231,47,39,255));
   // ui->status_te->append("ERROR: " + print_me);

    debug << "ERROR: " + print_me << endl;
}

////used for sending status messages to the gui, can be removed
void MainWindow::print_Status(QString print_me)
{
   // ui->status_te->setTextColor(QColor(0,0,0,100));
   // ui->status_te->append("STATUS: " + print_me);

    debug << "STATUS: " + print_me << endl;
}

//Loads all the different modules and parameters from the config file into QMaps declared in the guicomm_mw.h aswell as different GUI elements
void MainWindow::loadConfig()
{
    debug << "beginning of loadConfig()" << endl;//Crashes at this line, but not the next one

    //THIS IS CURRENT WHERE THIS CODE CRASHES

    debug << "here 1 ?" << endl;

    string temp_mname_s;
    string temp_pname_s;

    int temp_mval_i = 0;
    int temp_pval_i = 0;
    int row_count = 0;

    debug << "here 2 ?" << endl;
    module m1,m2,m3,m4,m5,m6,m7,m8,m9,m10;

    debug << "Right befoer the first module" << endl;



    //First thing is first
    //Read in the entire config file and place it in Module structs


    //This string of if statements method should be reduced to a few for loops only chaning the parameter names

    //MODULE1
    if(cfg.lookupValue("M1name",temp_mname_s))
    {
        row_count++;
        cfg.lookupValue("M1val", temp_mval_i);
        m1.name = QString::fromStdString(temp_mname_s);
        m1.value = temp_mval_i;
        m1.active = true;

        if(cfg.lookupValue("P1name1", temp_pname_s))
        {
            cfg.lookupValue("P1val1", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name2", temp_pname_s))
        {
            cfg.lookupValue("P1val2",temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name3", temp_pname_s))
        {
            cfg.lookupValue("P1val3", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name4", temp_pname_s))
        {
            cfg.lookupValue("P1val4", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name5", temp_pname_s))
        {
            cfg.lookupValue("P1val5", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name6", temp_pname_s))
        {
            cfg.lookupValue("P1val6", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name7", temp_pname_s))
        {
            cfg.lookupValue("P1val7", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name8", temp_pname_s))
        {
            cfg.lookupValue("P1val8", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name9", temp_pname_s))
        {
            cfg.lookupValue("P1val9", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P1name10", temp_pname_s))
        {
            cfg.lookupValue("P1val10", temp_pval_i);
            m1.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 1" << endl;
        }
        mod_map.insert(row_count,m1);
        debug << "The first Module from guicomm.cfg" << endl;
        debug << m1.name << "=" << m1.value << endl;

        QMap<QString, int>::const_iterator i = m1.parameters.constBegin();
        while (i != m1.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE2
    if(cfg.lookupValue("M2name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M2val", temp_mval_i);
        m2.name = QString::fromStdString(temp_mname_s);
        m2.value = temp_mval_i;
        m2.active = true;

        if(cfg.lookupValue("P2name1", temp_pname_s))
        {
            cfg.lookupValue("P2val1", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name2", temp_pname_s))
        {
            cfg.lookupValue("P2val2",temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name3", temp_pname_s))
        {
            cfg.lookupValue("P2val3", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name4", temp_pname_s))
        {
            cfg.lookupValue("P2val4", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name5", temp_pname_s))
        {
            cfg.lookupValue("P2val5", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name6", temp_pname_s))
        {
            cfg.lookupValue("P2val6", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name7", temp_pname_s))
        {
            cfg.lookupValue("P2val7", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name8", temp_pname_s))
        {
            cfg.lookupValue("P2val8", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name9", temp_pname_s))
        {
            cfg.lookupValue("P2val9", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P2name10", temp_pname_s))
        {
            cfg.lookupValue("P2val10", temp_pval_i);
            m2.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 2" << endl;
        }
        mod_map.insert(row_count,m2);
        debug << "The second Module from guicomm.cfg" << endl;
        debug << m2.name << "=" << m2.value << endl;

        QMap<QString, int>::const_iterator i = m2.parameters.constBegin();
        while (i != m2.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE3
    if(cfg.lookupValue("M3name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M3val", temp_mval_i);
        m3.name = QString::fromStdString(temp_mname_s);
        m3.value = temp_mval_i;
        m3.active = true;

        if(cfg.lookupValue("P3name1", temp_pname_s))
        {
            cfg.lookupValue("P3val1", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name2", temp_pname_s))
        {
            cfg.lookupValue("P3val2",temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name3", temp_pname_s))
        {
            cfg.lookupValue("P3val3", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name4", temp_pname_s))
        {
            cfg.lookupValue("P3val4", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name5", temp_pname_s))
        {
            cfg.lookupValue("P3val5", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name6", temp_pname_s))
        {
            cfg.lookupValue("P3val6", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name7", temp_pname_s))
        {
            cfg.lookupValue("P3val7", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name8", temp_pname_s))
        {
            cfg.lookupValue("P3val8", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name9", temp_pname_s))
        {
            cfg.lookupValue("P3val9", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P3name10", temp_pname_s))
        {
            cfg.lookupValue("P3val10", temp_pval_i);
            m3.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 3" << endl;
        }
        mod_map.insert(row_count,m3);
        debug << "The third Module from guicomm.cfg" << endl;
        debug << m3.name << "=" << m3.value << endl;

        QMap<QString, int>::const_iterator i = m3.parameters.constBegin();
        while (i != m3.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE4
    if(cfg.lookupValue("M4name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M4val", temp_mval_i);
        m4.name = QString::fromStdString(temp_mname_s);
        m4.value = temp_mval_i;
        m4.active = true;

        if(cfg.lookupValue("P4name1", temp_pname_s))
        {
            cfg.lookupValue("P4val1", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name2", temp_pname_s))
        {
            cfg.lookupValue("P4val2",temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name3", temp_pname_s))
        {
            cfg.lookupValue("P4val3", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name4", temp_pname_s))
        {
            cfg.lookupValue("P4val4", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name5", temp_pname_s))
        {
            cfg.lookupValue("P4val5", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name6", temp_pname_s))
        {
            cfg.lookupValue("P4val6", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name7", temp_pname_s))
        {
            cfg.lookupValue("P4val7", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name8", temp_pname_s))
        {
            cfg.lookupValue("P4val8", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name9", temp_pname_s))
        {
            cfg.lookupValue("P4val9", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P4name70", temp_pname_s))
        {
            cfg.lookupValue("P4val10", temp_pval_i);
            m4.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 4" << endl;
        }
        mod_map.insert(row_count,m4);
        debug << "The fourth Module from guicomm.cfg" << endl;
        debug << m4.name << "=" << m4.value << endl;

        QMap<QString, int>::const_iterator i = m4.parameters.constBegin();
        while (i != m4.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE5
    if(cfg.lookupValue("M5name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M5val", temp_mval_i);
        m5.name = QString::fromStdString(temp_mname_s);
        m5.value = temp_mval_i;
        m5.active = true;

        if(cfg.lookupValue("P5name1", temp_pname_s))
        {
            cfg.lookupValue("P5val1", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name2", temp_pname_s))
        {
            cfg.lookupValue("P5val2",temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name3", temp_pname_s))
        {
            cfg.lookupValue("P5val3", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name4", temp_pname_s))
        {
            cfg.lookupValue("P5val4", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name5", temp_pname_s))
        {
            cfg.lookupValue("P5val5", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name6", temp_pname_s))
        {
            cfg.lookupValue("P5val6", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name7", temp_pname_s))
        {
            cfg.lookupValue("P5val7", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name8", temp_pname_s))
        {
            cfg.lookupValue("P5val8", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name9", temp_pname_s))
        {
            cfg.lookupValue("P5val9", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P5name10", temp_pname_s))
        {
            cfg.lookupValue("P5va10l", temp_pval_i);
            m5.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 5" << endl;
        }
        mod_map.insert(row_count,m5);
        debug << "The fifth Module from guicomm.cfg" << endl;
        debug << m5.name << "=" << m5.value << endl;

        QMap<QString, int>::const_iterator i = m5.parameters.constBegin();
        while (i != m5.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE6
    if(cfg.lookupValue("M6name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M6val", temp_mval_i);
        m6.name = QString::fromStdString(temp_mname_s);
        m6.value = temp_mval_i;
        m6.active = true;

        if(cfg.lookupValue("P6name1", temp_pname_s))
        {
            cfg.lookupValue("P6val1", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name2", temp_pname_s))
        {
            cfg.lookupValue("P6val2",temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name3", temp_pname_s))
        {
            cfg.lookupValue("P6val3", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name4", temp_pname_s))
        {
            cfg.lookupValue("P6val4", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name5", temp_pname_s))
        {
            cfg.lookupValue("P6val5", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name6", temp_pname_s))
        {
            cfg.lookupValue("P6val6", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name7", temp_pname_s))
        {
            cfg.lookupValue("P6val7", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name8", temp_pname_s))
        {
            cfg.lookupValue("P6val8", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name9", temp_pname_s))
        {
            cfg.lookupValue("P6val9", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P6name10", temp_pname_s))
        {
            cfg.lookupValue("P6val10", temp_pval_i);
            m6.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 6" << endl;
        }
        mod_map.insert(row_count,m6);
        debug << "The sixth Module from guicomm.cfg" << endl;
        debug << m6.name << "=" << m6.value << endl;

        QMap<QString, int>::const_iterator i = m6.parameters.constBegin();
        while (i != m6.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE7
    if(cfg.lookupValue("M7name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M7val", temp_mval_i);
        m7.name = QString::fromStdString(temp_mname_s);
        m7.value = temp_mval_i;
        m7.active = true;

        if(cfg.lookupValue("P7name1", temp_pname_s))
        {
            cfg.lookupValue("P7val1", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name2", temp_pname_s))
        {
            cfg.lookupValue("P7val2",temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name3", temp_pname_s))
        {
            cfg.lookupValue("P7val3", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name4", temp_pname_s))
        {
            cfg.lookupValue("P7val4", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name5", temp_pname_s))
        {
            cfg.lookupValue("P7val5", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name6", temp_pname_s))
        {
            cfg.lookupValue("P7val6", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name7", temp_pname_s))
        {
            cfg.lookupValue("P7val7", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name8", temp_pname_s))
        {
            cfg.lookupValue("P7val8", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name9", temp_pname_s))
        {
            cfg.lookupValue("P7val9", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P7name10", temp_pname_s))
        {
            cfg.lookupValue("P7val10", temp_pval_i);
            m7.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 7" << endl;
        }
        mod_map.insert(row_count,m7);
        debug << "The seventh Module from guicomm.cfg" << endl;
        debug << m7.name << "=" << m7.value << endl;

        QMap<QString, int>::const_iterator i = m7.parameters.constBegin();
        while (i != m7.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE8
    if(cfg.lookupValue("M8name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M8val", temp_mval_i);
        m8.name = QString::fromStdString(temp_mname_s);
        m8.value = temp_mval_i;
        m8.active = true;

        if(cfg.lookupValue("P8name1", temp_pname_s))
        {
            cfg.lookupValue("P8val1", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name2", temp_pname_s))
        {
            cfg.lookupValue("P8val2",temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name3", temp_pname_s))
        {
            cfg.lookupValue("P8val3", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name4", temp_pname_s))
        {
            cfg.lookupValue("P8val4", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name5", temp_pname_s))
        {
            cfg.lookupValue("P8val5", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name6", temp_pname_s))
        {
            cfg.lookupValue("P8val6", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name7", temp_pname_s))
        {
            cfg.lookupValue("P8val7", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name8", temp_pname_s))
        {
            cfg.lookupValue("P8val8", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name9", temp_pname_s))
        {
            cfg.lookupValue("P8val9", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P8name10", temp_pname_s))
        {
            cfg.lookupValue("P8val10", temp_pval_i);
            m8.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 8" << endl;
        }
        mod_map.insert(row_count,m8);
        debug << "The eigth Module from guicomm.cfg" << endl;
        debug << m8.name << "=" << m8.value << endl;

        QMap<QString, int>::const_iterator i = m8.parameters.constBegin();
        while (i != m8.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE9
    if(cfg.lookupValue("M9name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M9val", temp_mval_i);
        m9.name = QString::fromStdString(temp_mname_s);
        m9.value = temp_mval_i;
        m9.active = true;

        if(cfg.lookupValue("P9name1", temp_pname_s))
        {
            cfg.lookupValue("P9val1", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name2", temp_pname_s))
        {
            cfg.lookupValue("P9val2",temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name3", temp_pname_s))
        {
            cfg.lookupValue("P9val3", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name4", temp_pname_s))
        {
            cfg.lookupValue("P9val4", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name5", temp_pname_s))
        {
            cfg.lookupValue("P9val5", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name6", temp_pname_s))
        {
            cfg.lookupValue("P9val6", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name7", temp_pname_s))
        {
            cfg.lookupValue("P9val7", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name8", temp_pname_s))
        {
            cfg.lookupValue("P9val8", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name9", temp_pname_s))
        {
            cfg.lookupValue("P9val9", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P9name10", temp_pname_s))
        {
            cfg.lookupValue("P9val10", temp_pval_i);
            m9.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 9" << endl;
        }
        mod_map.insert(row_count,m9);
        debug << "The nineth Module from guicomm.cfg" << endl;
        debug << m9.name << "=" << m9.value << endl;

        QMap<QString, int>::const_iterator i = m9.parameters.constBegin();
        while (i != m9.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }

    //MODULE10
    if(cfg.lookupValue("M10name",temp_mname_s))
    {

        row_count++;
        cfg.lookupValue("M10val", temp_mval_i);
        m10.name = QString::fromStdString(temp_mname_s);
        m10.value = temp_mval_i;
        m10.active = true;

        if(cfg.lookupValue("P10name1", temp_pname_s))
        {
            cfg.lookupValue("P10val1", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name2", temp_pname_s))
        {
            cfg.lookupValue("P10val2",temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name3", temp_pname_s))
        {
            cfg.lookupValue("P10val3", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name4", temp_pname_s))
        {
            cfg.lookupValue("P10val4", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name5", temp_pname_s))
        {
            cfg.lookupValue("P10val5", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name6", temp_pname_s))
        {
            cfg.lookupValue("P10val6", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name7", temp_pname_s))
        {
            cfg.lookupValue("P10val7", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name8", temp_pname_s))
        {
            cfg.lookupValue("P10val8", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name9", temp_pname_s))
        {
            cfg.lookupValue("P10val9", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        if(cfg.lookupValue("P10name10", temp_pname_s))
        {
            cfg.lookupValue("P10val10", temp_pval_i);
            m10.parameters.insert(QString::fromStdString(temp_pname_s),temp_pval_i);
        }
        else
        {
            debug << "The configuration file does not contain properly formatted parameters for Module 10" << endl;
        }
        mod_map.insert(row_count,m10);
        debug << "The tenth Module from guicomm.cfg" << endl;
        debug << m10.name << "=" << m10.value << endl;

        QMap<QString, int>::const_iterator i = m10.parameters.constBegin();
        while (i != m10.parameters.constEnd())
        {
            debug << i.key() << ": " << i.value() << endl;
            ++i;
        }
    }



    //FILL IN THE GUI
    if(m1.active)
    {
        foreach(module value, mod_map)
        {
             ui->module_cb->addItem(value.name);    //populate the combo box of modules
        }
    }
}

